name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Generate Reports
        shell: bash
        run: |
          npm install
          npm run reports
          npm run website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}